yabai fixed for devonthink, update b/config/karabiner/assets/complex_modifications/karabiner-shkrc.json and fix code error with bin/shkrc2karabiner.py

diff --git a/scripts/tmux-ssh-wrapper b/scripts/tmux-ssh-wrapper
--- a/scripts/tmux-ssh-wrapper
+++ b/scripts/tmux-ssh-wrapper
@@ -1,13 +1,38 @@
-#!/usr/bin/env bash
+#!/bin/bash -x
 
 # https://tools.ietf.org/html/rfc3986
 # $$URL$$ The complete url
 # schema://someone@
+# readonly URI_REGEX='^(([^:/?#]+):)?(//{0,1}+((([^:/?#[:alphanum:]]+)@)?([^:/?#]+)(:([0-9]+))?))?(/([^?#]*))(\?([^#]*))?(#(.*))?'
+#                    ↑↑          ↑      ↑↑↑             ↑        ↑↑           ↑ ↑        ↑  ↑        ↑ ↑
+#                    |2 scheme     |       ||6 userinfo        7 host    | 9 port       | 11 rpath |  13 query | 15 fragment 1 scheme:     |  |5 userinfo@             8 :…           10 path    12 ?…       14 #…
+#                                  |        4 authority
+#                                  3 //…
+
 readonly URI_REGEX='^(([^:/?#]+):)?(//?((([^:/?#]+)@)?([^:/?#]+)(:([0-9]+))?))?(/([^?#]*))(\?([^#]*))?(#(.*))?'
 #                    ↑↑            ↑  ↑↑↑            ↑         ↑ ↑            ↑ ↑        ↑  ↑        ↑ ↑
 #                    |2 scheme     |  ||6 userinfo   7 host    | 9 port       | 11 rpath |  13 query | 15 fragment 1 scheme:     |  |5 userinfo@             8 :…           10 path    12 ?…       14 #…
 #                                  |  4 authority
 #                                  3 //…
+function uri2json() {
+    set -a
+    local _URI_SCHEMA _URI_ABS_URI_PATH _URI_AUTHORITY _URI_USER _URI_HOST _URI_PORT _URI_PATH _URI_RPATH _URI_QUERY _URI_FRAGMENT  
+    if [[ "$*" =~ ${URI_REGEX} ]]; then 
+        if [[ ${#match[@]} -gt 0 ]]; then
+            for i in {0..${#match[@]}}; do
+                echo "${i} ${match[i]}"
+            done
+            # read -r _URI_MATCH <<< "${match[*]}"
+            read -r _URI_SCHEMA _URI_ABS_URI_PATH _URI_AUTHORITY _URI_REMAINING "$([[ ${match[11]} =~ '@' ]] && echo -n _URI_USER)" _URI_HOST _URI_PORT _URI_PATH _URI_RPATH _URI_QUERY _URI_FRAGMENT <<< "${match[@]}"
+            export _URI_SCHEMA _URI_ABS_URI_PATH _URI_AUTHORITY _URI_REMAINING _URI_USER _URI_HOST _URI_PORT _URI_PATH _URI_RPATH _URI_QUERY _URI_FRAGMENT
+            python3 -c 'import json, os;print(json.dumps({str(k[5:]): v for k, v in os.environ.items() if k.startswith("_URI_") or k == "match"}))'
+            return 0
+        fi 
+    fi
+    printf -- 'Invalid URL\n' >&2
+    set +a
+}
+
 
 parse_scheme () {
     [[ "$@" =~ $URI_REGEX ]] && echo "${BASH_REMATCH[2]}"
